apiVersion: apps/v1
kind: Deployment
metadata:
  name: owner-service
  namespace: yelp-lab2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owner-service
  template:
    metadata:
      labels:
        app: owner-service
    spec:
      containers:
        - name: owner-service
          image: yelp_backend_v2-owner_service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: yelp-config
            - secretRef:
                name: yelp-secrets
