apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: yelp-lab2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: yelp_backend_v2-restaurant_service:kafka1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: yelp-config
            - secretRef:
                name: yelp-secrets
