apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: yelp-lab2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: yelp_backend_v2-user_service:kafka2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: yelp-config
            - secretRef:
                name: yelp-secrets
