apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-worker
  namespace: yelp-lab2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-worker
  template:
    metadata:
      labels:
        app: user-worker
    spec:
      containers:
        - name: user-worker
          image: yelp_backend_v2-user_worker_service:kafka1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: yelp-config
            - secretRef:
                name: yelp-secrets
